# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 中介杂志
email: sinfaan@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: "" # the subpath of your site, e.g. /blog
url: "zzczzc20.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
include: ["_pages"]
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    bone:
      name:           Bone
      avatar:         assets/images/avatar1.jpg
      bio:            "坚持国际主义理想"
      email:          wowthemesnet@gmail.com
      twitter:        https://x.com/MediationMgzne

    claire:
      name:           Claire
      avatar:         assets/images/avatar2.jpg
      bio:            "feed the head"
      email:          fakemail@gmail.com
      twitter:        https://x.com/MediationMgzne

    hex:
      name:           Hex
      avatar:         assets/images/avatar3.jpg
      bio:            "Hi, I'm Hex"
      email:          fakemail@gmail.com
      twitter:        https://x.com/MediationMgzne

    棉籽:
      name:           棉籽
      avatar:         assets/images/avatar4.jpg
      bio:            "要去改變這個不斷生產出這些悲劇的世界"
      email:          fakemail@gmail.com
      twitter:        https://x.com/MediationMgzne

    万类霜天竞自由:
      name:           万类霜天竞自由
      avatar:         assets/images/avatar5.png
      bio:            "任何事物的内部都有其新旧两个方面的矛盾，形成为一系列的曲折的斗争。 斗争的结果，新的方面由小变大，上升为支配的东西；旧的方面则由大变小，变成逐步归于灭亡的东西。"
      email:          fakemail@gmail.com
      twitter:        https://x.com/MediationMgzne
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: bone
      avatar: /docs/assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
